package com.example.dllo.yohomix.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dllo.yohomix.bean.SearchItemBean;

import com.example.dllo.yohomix.bean.SearchItemBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchItemBeanDaoConfig;

    private final SearchItemBeanDao searchItemBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchItemBeanDaoConfig = daoConfigMap.get(SearchItemBeanDao.class).clone();
        searchItemBeanDaoConfig.initIdentityScope(type);

        searchItemBeanDao = new SearchItemBeanDao(searchItemBeanDaoConfig, this);

        registerDao(SearchItemBean.class, searchItemBeanDao);
    }
    
    public void clear() {
        searchItemBeanDaoConfig.clearIdentityScope();
    }

    public SearchItemBeanDao getSearchItemBeanDao() {
        return searchItemBeanDao;
    }

}
